- name: Restarts Service
  hosts: tag_Name_webserverA
  gather_facts: True
  become: True
  
  tasks: 
    -  name: restart
       shell: sudo systemctl status apache2
       register: output
    -  debug:
         msg: " {{ output }}"
