- name: Restarts Service
  hosts: localhost 
  gather_facts: True
  become: False
  
  tasks: 
    -  name: restart
       shell: sudo systemctl status apache2
       register: output
    -  debug:
         msg: " {{ output }}"
