- name: Restarts Service
  hosts: all
  gather_facts: True
  become: True
  
  tasks: 
    -  name: restart
       shell: systemctl status apache2
       register: output
    -  debug:
         msg: " {{ output }}"
