- name: Restarts Service
  hosts:  
    ansible_host: webserverA
      ansible_user: sidharth
  gather_facts: True
  become: True
  
  tasks: 
    -  name: restart
       shell: sudo systemctl status apache2
       register: output
    -  debug:
         msg: " {{ output }}"
